name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - demo

jobs:
  deploy:
    name: Deploy API and Jobs to Cloud Run
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Deploy API to Cloud Run
      run: |
        gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/bigdata-api
        gcloud run deploy bigdata-api \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/bigdata-api \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated

    - name: Deploy Backup Job to Cloud Run
      run: |
        gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/bigdata-backup
        gcloud run deploy bigdata-backup \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/bigdata-backup \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated

    - name: Deploy Restore Job to Cloud Run
      run: |
        gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/bigdata-restore
        gcloud run deploy bigdata-restore \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/bigdata-restore \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated
